### PR TITLE
Create 2020-11-18-larasati-updated-final-milestones.md

### PR DESCRIPTION
**Pull request by a-larasati**

### CODE REVIEW

**Review by pccisme — CHANGES_REQUESTED** [review]
Looks good to me. But one thing I want to point out is that I see your un-checked checkboxes are not working right now. You may want to leave a single space between the brackets to make them work!

**Review by brianna-stedman — APPROVED** [review]
totally feel the loss in motivation as well. you're killing it, though, and this looks like a cool tool that you are building. we got this! :-)
ps I think Patrick pointed out that your brackets need a space to turn into checkboxes, if you want to change that before merging

**Comment by a-larasati** [comment]
@brianna-stedman @pccisme Thanks for catching that ❤️ ready for review

**Review by pccisme — APPROVED** [review]
Great job!!!!

**Pull request merged**
