### PR TITLE
Update titles & author name for every file. 

### PR DESCRIPTION
**Pull request by EAkita**
I think I have everything done correctly. I wanted to go back into each file and double check one more time to make sure that the code is all good, and the reflections are up to date. This will take a day or two. 
Thanks!

### CODE REVIEW

**Comment by EAkita** [comment]
@MishaCienfuegos  Please merge with production., Thanks!

**Review by MishaCienfuegos — COMMENTED** [review]
This all looks good so far!

**Review by MishaCienfuegos — APPROVED** [review]
This all looks good! 👍 

Are you still making changes, or are you ready for these to be merged? If the latter, you'll want to change the status from Draft to Pull Request.

**Comment by eah13** [comment]
@EAkita see Misha's question above. Can we merge this PR? If so, click 'Ready for review' to take off the draft status

**Comment by EAkita** [comment]
@MishaCienfuegos 
Just clicked the "Ready to review" button and merged branches. Hopefully it shows up on the class website.

**Pull request merged**
