### PR TITLE
Create 2020-10-14-app_milestones_draft-intjnotinfp.md

### PR DESCRIPTION
**Pull request by ghost**
Here's my milestone outline. Please check the formatting! @KJEZ35

### CODE REVIEW

**Comment by KJEZ35** [comment]
Everything looks great!

**Comment by KJEZ35** [comment]
@intjnotinfp For some reason I am unable to merge your pull request. Can you try assigning me as the reviewer?

**Comment by ghost** [comment]
I added you as review and assignee. Can you let me know if that worked/ now you can merge it? @KJEZ35

**Review by KJEZ35 — APPROVED** [review]
Looks great!

**Comment by KJEZ35** [comment]
@intjnotinfp I merged the request! I should be done with mine shortly.

**Comment by ghost** [comment]
Sounds good, thanks!

**Pull request merged**
