### PR TITLE
Added/edited About line of profile

### PR DESCRIPTION
**Pull request by a-larasati**
Ready for review/merge

### CODE REVIEW

**Review by brianna-stedman — APPROVED** [review]
looks good to me!

**Comment by brianna-stedman** [comment]
@a-larasati I approved this but noticed that you used 1st person instead of 3rd person in your bio. It's up to you if you want to change it before it's merged, looks like the example is 3rd person, but I'm sure it's a personal preference

**Comment by a-larasati** [comment]
@brianna-stedman Yeah I'll make that change really quickly and then will ping you again

**Review by brianna-stedman — APPROVED** [review]
perf

**Comment by brianna-stedman** [comment]
@a-larasati merged!

**Pull request merged**
