### PR TITLE
Spaceranger-23 TreasureHunt.md

### PR DESCRIPTION
**Pull request by spaceranger-23**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Reginald, this looks like a great placeholder. @me later on once you've added your code and reflections and I'll review those changes.

Make sure to add quotation marks around your title and add your username somewhere in the _post/ section so that it's uniquely identified.

Great job making sure your title is human readable!

**Comment by spaceranger-23** [comment]
Pull request ready for review!

**Review by MishaCienfuegos — CHANGES_REQUESTED** [review]
Great job using Markdown to format this post! :octocat: 

The file path looks a little off. Could you update this to resemble your other posts' path structures? Thanks!

**Comment by spaceranger-23** [comment]
@MishaCienfuegos  forgot the slash in the file between my username and the date. Should be ready to go now. Thanks

**Review by MishaCienfuegos — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
