### PR TITLE
Martinrb84_2020-08-26-first-post.md

### PR DESCRIPTION
**Pull request by Martinrb84**
I enrolled in this course late and I am trying to watch the recording of the first day of class and work through it!

### CODE REVIEW

**Review by Martinrb84 — COMMENTED** [review]
Add more to your introduction please.

**Review by eah13 — CHANGES_REQUESTED** [review]
Everything looks good, except for two things: 
* `<username>` was meant to be replaced by your github username. So in this case you'll want to edit the file (from the Files Changed tab). The filename box will start at `2020-08-...`, the actual filename, but if you move all the way to the left and press backspace it'll make the folder name `<username>` editable for you. You can then replace that with `Martinrb84`
* Your github username should also go in the `author:` field, instead of `mbeni`, so go ahead and edit that while you're editing the filename. Or, if you want to do it in a second commit that's fine too. Repeat the steps to edit the file and change what comes after `author:`

**Comment by Martinrb84** [comment]
Think I updated it correctly.

**Review by Martinrb84 — COMMENTED** [review]
Think I updated your suggestions correctly.

**Comment by eah13** [comment]
Closing for now.

**Pull request closed without merging**
