### PR TITLE
Create Liz Bender Trinket Post.md

### PR DESCRIPTION
**Pull request by benderliz**
This is my first writing code reflection using GitHub.

### CODE REVIEW

**Comment by benderliz** [comment]
Test comment!

**Comment by itohosagie** [comment]
Glad this was a lightbulb moment!

**Review by Elizard0926 — COMMENTED** [review]
This is a very cool example of how a new concept reinforced a past one. Very happy for you that you had this lightbulb moment!

**Review by MishaCienfuegos — APPROVED** [review]
Good use of markdown to format your code! You can just use single backticks around the inline code, but the file preview makes it look like GitHub still displays it as code with two.

I did add the date (YYYY-MM-DD) to your file name so it shows up where we expect it in the class website.

**Pull request merged**
